/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestTermsRouteImport } from './routes/_guest/terms'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestPrivacyRouteImport } from './routes/_guest/privacy'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthContactsRouteImport } from './routes/_auth/contacts'
import { Route as AuthCampaignsRouteImport } from './routes/_auth/campaigns'
import { Route as AuthMessagesRouteRouteImport } from './routes/_auth/messages/route'
import { Route as AuthMessagesIndexRouteImport } from './routes/_auth/messages/index'
import { Route as AuthMessagesConversationIdRouteImport } from './routes/_auth/messages/$conversationId'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestTermsRoute = GuestTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestPrivacyRoute = GuestPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCampaignsRoute = AuthCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMessagesRouteRoute = AuthMessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMessagesIndexRoute = AuthMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMessagesRouteRoute,
} as any)
const AuthMessagesConversationIdRoute =
  AuthMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthMessagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/$': typeof SplatRoute
  '/messages': typeof AuthMessagesRouteRouteWithChildren
  '/campaigns': typeof AuthCampaignsRoute
  '/contacts': typeof AuthContactsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/privacy': typeof GuestPrivacyRoute
  '/signup': typeof GuestSignupRoute
  '/terms': typeof GuestTermsRoute
  '/messages/$conversationId': typeof AuthMessagesConversationIdRoute
  '/messages/': typeof AuthMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/$': typeof SplatRoute
  '/campaigns': typeof AuthCampaignsRoute
  '/contacts': typeof AuthContactsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/login': typeof GuestLoginRoute
  '/privacy': typeof GuestPrivacyRoute
  '/signup': typeof GuestSignupRoute
  '/terms': typeof GuestTermsRoute
  '/messages/$conversationId': typeof AuthMessagesConversationIdRoute
  '/messages': typeof AuthMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_auth/messages': typeof AuthMessagesRouteRouteWithChildren
  '/_auth/campaigns': typeof AuthCampaignsRoute
  '/_auth/contacts': typeof AuthContactsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/privacy': typeof GuestPrivacyRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_guest/terms': typeof GuestTermsRoute
  '/_guest/': typeof GuestIndexRoute
  '/_auth/messages/$conversationId': typeof AuthMessagesConversationIdRoute
  '/_auth/messages/': typeof AuthMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/messages'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/messages/$conversationId'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/messages/$conversationId'
    | '/messages'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/$'
    | '/_auth/messages'
    | '/_auth/campaigns'
    | '/_auth/contacts'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_guest/login'
    | '/_guest/privacy'
    | '/_guest/signup'
    | '/_guest/terms'
    | '/_guest/'
    | '/_auth/messages/$conversationId'
    | '/_auth/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/terms': {
      id: '/_guest/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof GuestTermsRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/privacy': {
      id: '/_guest/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof GuestPrivacyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/campaigns': {
      id: '/_auth/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthCampaignsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/messages/': {
      id: '/_auth/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthMessagesIndexRouteImport
      parentRoute: typeof AuthMessagesRouteRoute
    }
    '/_auth/messages/$conversationId': {
      id: '/_auth/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthMessagesConversationIdRouteImport
      parentRoute: typeof AuthMessagesRouteRoute
    }
  }
}

interface AuthMessagesRouteRouteChildren {
  AuthMessagesConversationIdRoute: typeof AuthMessagesConversationIdRoute
  AuthMessagesIndexRoute: typeof AuthMessagesIndexRoute
}

const AuthMessagesRouteRouteChildren: AuthMessagesRouteRouteChildren = {
  AuthMessagesConversationIdRoute: AuthMessagesConversationIdRoute,
  AuthMessagesIndexRoute: AuthMessagesIndexRoute,
}

const AuthMessagesRouteRouteWithChildren =
  AuthMessagesRouteRoute._addFileChildren(AuthMessagesRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthMessagesRouteRoute: typeof AuthMessagesRouteRouteWithChildren
  AuthCampaignsRoute: typeof AuthCampaignsRoute
  AuthContactsRoute: typeof AuthContactsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMessagesRouteRoute: AuthMessagesRouteRouteWithChildren,
  AuthCampaignsRoute: AuthCampaignsRoute,
  AuthContactsRoute: AuthContactsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPrivacyRoute: typeof GuestPrivacyRoute
  GuestSignupRoute: typeof GuestSignupRoute
  GuestTermsRoute: typeof GuestTermsRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestPrivacyRoute: GuestPrivacyRoute,
  GuestSignupRoute: GuestSignupRoute,
  GuestTermsRoute: GuestTermsRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
