/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthPublicRouteImport } from './routes/_auth-public'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GuestIndexRouteImport } from './routes/_guest.index'
import { Route as AppUpcomingRouteImport } from './routes/app.upcoming'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPomodoroRouteImport } from './routes/app.pomodoro'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as GuestTermsOfServiceRouteImport } from './routes/_guest.terms-of-service'
import { Route as GuestPrivacyPolicyRouteImport } from './routes/_guest.privacy-policy'
import { Route as AuthPublicSignupRouteImport } from './routes/_auth-public.signup'
import { Route as AuthPublicLoginRouteImport } from './routes/_auth-public.login'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPublicRoute = AuthPublicRouteImport.update({
  id: '/_auth-public',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const AppUpcomingRoute = AppUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const GuestTermsOfServiceRoute = GuestTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => GuestRoute,
} as any)
const GuestPrivacyPolicyRoute = GuestPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => GuestRoute,
} as any)
const AuthPublicSignupRoute = AuthPublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthPublicRoute,
} as any)
const AuthPublicLoginRoute = AuthPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthPublicRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof GuestIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof AuthPublicLoginRoute
  '/signup': typeof AuthPublicSignupRoute
  '/privacy-policy': typeof GuestPrivacyPolicyRoute
  '/terms-of-service': typeof GuestTermsOfServiceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof GuestIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof AuthPublicLoginRoute
  '/signup': typeof AuthPublicSignupRoute
  '/privacy-policy': typeof GuestPrivacyPolicyRoute
  '/terms-of-service': typeof GuestTermsOfServiceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth-public': typeof AuthPublicRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_auth-public/login': typeof AuthPublicLoginRoute
  '/_auth-public/signup': typeof AuthPublicSignupRoute
  '/_guest/privacy-policy': typeof GuestPrivacyPolicyRoute
  '/_guest/terms-of-service': typeof GuestTermsOfServiceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/_guest/': typeof GuestIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/pomodoro'
    | '/app/settings'
    | '/app/today'
    | '/app/upcoming'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/pomodoro'
    | '/app/settings'
    | '/app/today'
    | '/app/upcoming'
    | '/app/projects/$projectId'
    | '/app/projects'
  id:
    | '__root__'
    | '/$'
    | '/_auth-public'
    | '/_guest'
    | '/app'
    | '/_auth-public/login'
    | '/_auth-public/signup'
    | '/_guest/privacy-policy'
    | '/_guest/terms-of-service'
    | '/app/calendar'
    | '/app/inbox'
    | '/app/pomodoro'
    | '/app/settings'
    | '/app/today'
    | '/app/upcoming'
    | '/_guest/'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthPublicRoute: typeof AuthPublicRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-public': {
      id: '/_auth-public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/app/upcoming': {
      id: '/app/upcoming'
      path: '/upcoming'
      fullPath: '/app/upcoming'
      preLoaderRoute: typeof AppUpcomingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pomodoro': {
      id: '/app/pomodoro'
      path: '/pomodoro'
      fullPath: '/app/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/terms-of-service': {
      id: '/_guest/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof GuestTermsOfServiceRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/privacy-policy': {
      id: '/_guest/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof GuestPrivacyPolicyRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth-public/signup': {
      id: '/_auth-public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthPublicSignupRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/_auth-public/login': {
      id: '/_auth-public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthPublicLoginRouteImport
      parentRoute: typeof AuthPublicRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthPublicRouteChildren {
  AuthPublicLoginRoute: typeof AuthPublicLoginRoute
  AuthPublicSignupRoute: typeof AuthPublicSignupRoute
}

const AuthPublicRouteChildren: AuthPublicRouteChildren = {
  AuthPublicLoginRoute: AuthPublicLoginRoute,
  AuthPublicSignupRoute: AuthPublicSignupRoute,
}

const AuthPublicRouteWithChildren = AuthPublicRoute._addFileChildren(
  AuthPublicRouteChildren,
)

interface GuestRouteChildren {
  GuestPrivacyPolicyRoute: typeof GuestPrivacyPolicyRoute
  GuestTermsOfServiceRoute: typeof GuestTermsOfServiceRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestPrivacyPolicyRoute: GuestPrivacyPolicyRoute,
  GuestTermsOfServiceRoute: GuestTermsOfServiceRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppUpcomingRoute: typeof AppUpcomingRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppInboxRoute: AppInboxRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppUpcomingRoute: AppUpcomingRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthPublicRoute: AuthPublicRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
