name: Test
on:
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build dependencies
        run: npx turbo build --filter='./packages/**'

      - name: Run lint
        run: npx turbo lint --filter=invoice

      - name: Build Frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npx turbo build --filter=invoice
